# This is the list of my currently owned cities.
def getMyAirportList() :
    return [
        'Aden',
        'Al Fashir',
        'Algiers',
        'Atlanta',
        'Baghdad',
        'Bangalore',
        'Barcelona',
        'Beijing',
        'Berlin',
        'Bogota',
        'Boston',
        'Broome',
        'Buenos Aires',
        'Cairo',
        'Caracas',
        'Chengdu',
        'Chicago',
        'Cuiaba',
        'Dakar',
        'Dallas',
        'Delhi',
        'Detroit',
        'Dhaka',
        'Guangzhou',
        'Guatemala',
        'Hanoi',
        'Harbin',
        'Hong Kong',
        'Honolulu',
        'Houston',
        'Hyderabad',
        'Istanbul',
        'Jakarta',
        'Johannesburg',
        'Kabul',
        'Kaduna',
        'Karachi',
        'Katherine',
        'Khartoum',
        'Kinshasa',
        'Kolkata',
        'Lagos',
        'Lima',
        'London',
        'Los Angeles',
        'Madrid',
        'Manila',
        'Melbourne',
        'Mexico City',
        'Miami',
        'Mogadishu',
        'Monrovia',
        'Monterrey',
        'Moscow',
        'Mumbai',
        'Muscat',
        'Nairobi',
        'New York',
        'Novosibirsk',
        'Osaka',
        'Paris',
        'Perm',
        'Philadelphia',
        'Phoenix',
        'Rangoon',
        'Recife',
        'Rio de Janeiro',
        'Riyadh',
        'Salvador',
        'San Francisco',
        'Santiago',
        'Sao Paolo',
        'Seattle',
        'Seoul',
        'Shanghai',
        'Shenyang',
        'Singapore',
        'St. Petersburg',
        'Sydney',
        'Taipei',
        'Tehran',
        'Teresina',
        'Tokyo',
        'Toronto',
        'Tripoli',
        'Volgograd',
        'Washington D.C.',
        'Xi\'an',
        'Xining',
        ]
